export const GET_ALL_TODOS = 'GET_ALL_TODOS';
export const GET_ALL_TODOS_SUCCESS = 'GET_ALL_TODOS_SUCCESS';
export const GET_ALL_TODOS_FAILED = 'GET_ALL_TODOS_FAILED';
export const ADD_TODO = 'ADD_TODO';
export const GET_ALL_BUCKETS='GET_ALL_BUCKETS';
export const GET_ALL_BUCKETS_SUCCESS='GET_ALL_BUCKETS_SUCCESS';
export const GET_ALL_BUCKETS_FAILED='GET_ALL_BUCKETS_FAILED';
